{% set version = "0.24.0" %}

package:
  name: gym
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gym/gym-{{ version }}.tar.gz
  sha256: 69f96424be40d23088be978b61f45c23911e2ccddafad08cf2fac608e8bd86e4

build:
  number: 0

# Need these up here for conda-smithy to handle them properly.
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
  run:
    - python

outputs:
  - name: gym
    build:
      script: {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - python
        - pip
        - cloudpickle >=1.2.0
        - numpy
      run:
        - python
        - cloudpickle >=1.2.0
        - numpy
        - importlib_metadata >=4.8.1  # [py<=39]
    test:
      requires:
        - mock
        - pytest
      imports:
        - gym
      commands:
        # TODO: run test suite

  - name: gym-all
    requirements:
      host:
        - python
      run:
        - python
        # exclude gym-atari package because the Atari-Py dependency
        # has been replaced with ALE-py which has not yet been
        # packaged in conda-forge, see conda-forge/staged-recipes#16488
        # - {{ pin_subpackage('gym-atari', exact=True) }}
        - {{ pin_subpackage('gym-box2d', exact=True) }}
        - {{ pin_subpackage('gym-classic_control', exact=True) }}
        - {{ pin_subpackage('gym-mujoco', exact=True) }}
        - {{ pin_subpackage('gym-toy_text', exact=True) }}
        - {{ pin_subpackage('gym-other', exact=True) }}
    test:
      imports:
        - gym

  - name: gym-atari
    build:
      # the Atari-Py dependency has been replaced with ALE-Py
      # which has not yet been packaged in conda-forge
      skip: true
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        - ale-py >=0.7.1,<0.8
    test:
      imports:
        - gym.envs.atari

  - name: gym-box2d
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        - box2d-py ==2.3.8
        - pyglet >=1.4.0
    test:
      imports:
        - gym.envs.box2d

  - name: gym-classic_control
    requirements:
      host:
        - python
      run:
        - python
        - pyglet >=1.4.0
        - {{ pin_subpackage('gym', exact=True) }}
        # no extra dependencies for this combination
    test:
      imports:
        - gym.envs.classic_control

  - name: gym-mujoco
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        - mujoco-python
        - imageio
    test:
      imports:
        - gym.envs.mujoco

  - name: gym-toy_text
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        - scipy >=1.4.1
    test:
      imports:
        - gym.envs.toy_text

  - name: gym-other
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        - lz4 >=3.1.0
        - opencv >=3.0
    test:
      imports:
        # There are no tests in the source code for gym-other

about:
  home: https://github.com/openai/gym
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'The OpenAI Gym: A toolkit for developing and comparing your reinforcement learning agents.'
  description: 'The OpenAI Gym: A toolkit for developing and comparing your reinforcement learning agents.'
  doc_url: https://gym.openai.com/docs/
  dev_url: https://github.com/openai/gym

extra:
  recipe-maintainers:
    - h-vetinari
    - jkterry1
    - pseudo-rnd-thoughts
    - thewchan
