{% set version = "0.17.3" %}

package:
  name: gym
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gym/gym-{{ version }}.tar.gz
  sha256: 96a7dd4e9cdb39e30c7a79e5773570fd9408f7fdb58c714c293cfbb314818eb6

build:
  number: 2

# Need these up here for conda-smithy to handle them properly.
requirements:
  host:
    - python
  run:
    - python

outputs:
  - name: gym
    build:
      script: {{ PYTHON }} -m pip install . -vv
    requirements:
      host:
        - python
        - pip
        - cloudpickle >=1.2.0,<1.7.0
        - numpy
        - pyglet >=1.4.0
        - scipy
      run:
        - python
        - cloudpickle >=1.2.0,<1.7.0
        - numpy
        - pyglet >=1.4.0
        - scipy
    test:
      requires:
        - mock
        - pytest
      imports:
        - gym

  - name: gym-all
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym-atari', exact=True) }}
        - {{ pin_subpackage('gym-box2d', exact=True) }}
        - {{ pin_subpackage('gym-classic_control', exact=True) }}
        # exclude some packages because their dependency (mujoco) has
        # incompatible license, see below
        #- {{ pin_subpackage('gym-mujoco', exact=True) }}
        #- {{ pin_subpackage('gym-robotics', exact=True) }}
    test:
      imports:
        - gym

  - name: gym-atari
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        - atari_py ==0.2.6
        - opencv
        - pillow
    test:
      imports:
        - gym.envs.atari

  - name: gym-box2d
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        - box2d-py ==2.3.8
    test:
      imports:
        - gym.envs.box2d

  - name: gym-classic_control
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        # no extra dependencies for this combination
    test:
      imports:
        - gym.envs.classic_control

  - name: gym-mujoco
    build:
      # mujoco-py cannot be packaged for license reasons, see
      # https://github.com/openai/mujoco-py#install-mujoco
      skip: true
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        - mujoco-py >=1.50,<2.0
        - imageio
    test:
      imports:
        - gym.envs.mujoco

  - name: gym-robotics
    build:
      # mujoco-py cannot be packaged for license reasons, see
      # https://github.com/openai/mujoco-py#install-mujoco
      skip: true
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        - mujoco-py >=1.50,<2.0
        - imageio
    test:
      imports:
        - gym.envs.robotics

about:
  home: https://github.com/openai/gym
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'The OpenAI Gym: A toolkit for developing and comparing your reinforcement learning agents.'
  description: 'The OpenAI Gym: A toolkit for developing and comparing your reinforcement learning agents.'
  doc_url: https://gym.openai.com/docs/
  dev_url: https://github.com/openai/gym

extra:
  recipe-maintainers:
    - h-vetinari
    - oblute
