{% set version = "1.0.0" %}

package:
  name: gymnasium-split
  version: {{ version }}

source:
  url: https://github.com/Farama-Foundation/Gymnasium/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d61a54c70d1960a0b64c63fe87edc30a0bac09551c27d8d94c36c54bf5fae5d9
  patches:
    # backport https://github.com/Farama-Foundation/Gymnasium/pull/1222
    - patches/1222.patch

build:
  number: 0

# Need these up here for conda-smithy to handle them properly.
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

outputs:
  - name: gymnasium
    build:
      script: {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
      host:
        - python
        - pip
        - setuptools
        - cloudpickle >=1.2.0
        - numpy
      run:
        - python
        - cloudpickle >=1.2.0
        - farama-notifications
        - numpy
        - jax-jumpy >=1.0.0
        - typing_extensions >=4.3.0
        - importlib_metadata >=4.8.1  # [py<=39]
    test:
      imports:
        - gymnasium

  - name: gymnasium-all
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gymnasium-atari', exact=True) }}
        - {{ pin_subpackage('gymnasium-box2d', exact=True) }}
        - {{ pin_subpackage('gymnasium-classic_control', exact=True) }}
        - {{ pin_subpackage('gymnasium-mujoco', exact=True) }}
        # see below
        # - {{ pin_subpackage('gymnasium-mujoco_py', exact=True) }}
        - {{ pin_subpackage('gymnasium-toy_text', exact=True) }}
        - {{ pin_subpackage('gymnasium-other', exact=True) }}
    test:
      source_files:
        - tests/
      requires:
        - mock
        - pytest
        - scipy
        - dill
        - pip
        - jax >=0.4  # [osx or linux64]
        - flax >=0.5.0  # [osx or linux64]
        - mesalib  # [linux]
        # Just for tests a newer version of mujoco is required
        # See https://github.com/Farama-Foundation/Gymnasium/pull/1221#issuecomment-2424973616
        - mujoco-python >=2.3.6
      commands:
        - pip check
        {% set tests_to_skip = "_not_a_real_test" %}
        # These test requires mujoco_py, see https://github.com/conda-forge/gymnasium-feedstock/pull/36#issuecomment-2124082918
        {% set tests_to_skip = tests_to_skip + " or test_verify_info_x_position" %}
        {% set tests_to_skip = tests_to_skip + " or test_verify_info_y_position" %}
        {% set tests_to_skip = tests_to_skip + " or test_verify_info_x_velocity" %}
        {% set tests_to_skip = tests_to_skip + " or test_verify_info_y_velocity" %}
        {% set tests_to_skip = tests_to_skip + " or test_verify_info_xy_velocity_xpos" %}
        {% set tests_to_skip = tests_to_skip + " or test_verify_info_xy_velocity_com" %}
        {% set tests_to_skip = tests_to_skip + " or test_set_state" %}
        {% set tests_to_skip = tests_to_skip + " or test_distance_from_origin_info" %}
        {% set tests_to_skip = tests_to_skip + " or test_model_sensors" %}
        {% set tests_to_skip = tests_to_skip + " or test_reset_noise_scale" %}
        # These tests do not run on CI due to missing window system, see https://github.com/conda-forge/gymnasium-feedstock/pull/36#issuecomment-2124183361
        {% set tests_to_skip = tests_to_skip + " or test_max_geom_attribute[10-human]" %}
        {% set tests_to_skip = tests_to_skip + " or test_max_geom_attribute[100-human]" %}
        {% set tests_to_skip = tests_to_skip + " or test_max_geom_attribute[1000-human]" %}
        {% set tests_to_skip = tests_to_skip + " or test_max_geom_attribute[10000-human]" %}
        # the following pygame tests are skipped [according to selector], because there is no rendering support during the CI build
        {% set tests_to_skip = tests_to_skip + " or test_human_rendering" %}                    # [osx]
        {% set tests_to_skip = tests_to_skip + " or test_keyboard_irrelevant_keydown_event" %}  # [osx]
        {% set tests_to_skip = tests_to_skip + " or test_keyboard_keyup_event" %}               # [osx]
        {% set tests_to_skip = tests_to_skip + " or test_keyboard_quit_event" %}                # [osx]
        {% set tests_to_skip = tests_to_skip + " or test_keyboard_relevant_keydown_event" %}    # [osx]
        {% set tests_to_skip = tests_to_skip + " or test_no_error_warnings[env0]" %}            # [osx]
        {% set tests_to_skip = tests_to_skip + " or test_no_error_warnings[env1]" %}            # [osx]
        {% set tests_to_skip = tests_to_skip + " or test_play_loop_real_env" %}                 # [osx]
        {% set tests_to_skip = tests_to_skip + " or test_play_relevant_keys" %}                 # [osx]
        {% set tests_to_skip = tests_to_skip + " or test_pygame_quit_event" %}                  # [osx]
        {% set tests_to_skip = tests_to_skip + " or test_video_size_no_zoom" %}                 # [osx]
        {% set tests_to_skip = tests_to_skip + " or test_video_size_zoom" %}                    # [osx]
        # The following tests fail as for mujoco the osmesa rendering backend is only supported on Linux
        # See https://github.com/conda-forge/gymnasium-feedstock/pull/41#issuecomment-2428691450
        {% set tests_to_skip = tests_to_skip + " or test_offscreen_viewer_custom_dimensions" %}   # [osx or win]
        {% set tests_to_skip = tests_to_skip + " or test_max_geom_attribute" %}                   # [osx or win]
        {% set tests_to_skip = tests_to_skip + " or test_camera_id" %}                            # [osx or win]
        {% set tests_to_skip = tests_to_skip + " or test_num_envs_screen_size" %}                 # [osx or win]
        # See https://github.com/conda-forge/gymnasium-feedstock/pull/32#issuecomment-2031810613
        {% set tests_to_skip = tests_to_skip + " or test_render_modes" %}                       # [aarch64]
        # atary test are skipped as we do not have atari ROMs in the CI
        # See https://github.com/conda-forge/gymnasium-feedstock/pull/41#issuecomment-2404215826
        - rm tests/wrappers/test_atari_preprocessing.py  # [unix]
        - del tests\\wrappers\\test_atari_preprocessing.py  # [win]
        # need to specify opengl driver on linux to enable offscreen rendering in MuJoCo
        - export MUJOCO_GL="osmesa"  # [linux]
        # Ensure that pygame tests pass on osx,
        # see https://github.com/conda-forge/gymnasium-feedstock/pull/36#issuecomment-2124699477
        - export SDL_VIDEODRIVER="dummy"  # [osx]
        - pytest -v tests/ -k "not ({{ tests_to_skip }})"

  - name: gymnasium-atari
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gymnasium', exact=True) }}
        - ale-py >=0.9
    test:
      commands:
        - echo "tested in ale-py"

  - name: gymnasium-box2d
    requirements:
      host:
        - python
        - swig ==4.*
      run:
        - python
        - {{ pin_subpackage('gymnasium', exact=True) }}
        - box2d-py ==2.3.*
        - pygame >=2.1.3
    test:
      imports:
        - gymnasium.envs.box2d

  - name: gymnasium-classic_control
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gymnasium', exact=True) }}
        - pygame >=2.1.3
    test:
      imports:
        - gymnasium.envs.classic_control

  - name: gymnasium-mujoco
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gymnasium', exact=True) }}
        - mujoco-python >=2.1.5
        - imageio >=2.14.1
    test:
      imports:
        - gymnasium.envs.mujoco

  - name: gymnasium-mujoco_py
    build:
      # we currently don't have https://github.com/openai/mujoco-py
      # in conda-forge, and it'll be replaced by mujoco anyway
      skip: true
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gymnasium', exact=True) }}
        - mujoco-py >=2.1,<2.2
        - imageio >=2.14.1
    test:
      imports:
        - gymnasium.envs.mujoco

  - name: gymnasium-toy_text
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gymnasium', exact=True) }}
        - pygame >=2.1.3
    test:
      imports:
        - gymnasium.envs.toy_text

  - name: gymnasium-other
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gymnasium', exact=True) }}
        - lz4 >=3.1.0
        - matplotlib >=3.0
        - moviepy >=1.0
        - py-opencv >=3.0
        - pytorch >=1.0  # [unix and not ppc64le]
    test:
      imports:
        # There are no tests in the source code for gymnasium-other

about:
  home: https://gymnasium.farama.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A standard API for reinforcement learning and a diverse set of reference environments (formerly Gym)
  dev_url: https://github.com/Farama-Foundation/Gymnasium

extra:
  recipe-maintainers:
    - h-vetinari
    - pseudo-rnd-thoughts
    - thewchan
    - traversaro
  feedstock-name: gymnasium
