{% set version = "0.28.1" %}

package:
  name: gymnasium-split
  version: {{ version }}

source:
  url: https://github.com/Farama-Foundation/Gymnasium/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 59dddc9ba631ed353cb6983cb3fff113c8619ef03142fd8474aa56bfccf9c424

build:
  number: 0

# Need these up here for conda-smithy to handle them properly.
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

outputs:
  - name: gymnasium
    build:
      script: {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
      host:
        - python
        - pip
        - cloudpickle >=1.2.0
        - numpy
      run:
        - python
        - cloudpickle >=1.2.0
        - gymnasium-notices
        - numpy
        - jax-jumpy
        - typing_extensions
        - importlib_metadata >=4.8.1  # [py<=39]
    test:
      imports:
        - gymnasium

  - name: gymnasium-all
    requirements:
      host:
        - python
      run:
        - python
        # see below
        # - {{ pin_subpackage('gymnasium-atari', exact=True) }}
        - {{ pin_subpackage('gymnasium-box2d', exact=True) }}
        - {{ pin_subpackage('gymnasium-classic_control', exact=True) }}
        - {{ pin_subpackage('gymnasium-mujoco', exact=True) }}
        # see below
        # - {{ pin_subpackage('gymnasium-mujoco_py', exact=True) }}
        - {{ pin_subpackage('gymnasium-toy_text', exact=True) }}
        - {{ pin_subpackage('gymnasium-other', exact=True) }}
    test:
      source_files:
        - tests/
      requires:
        - mock
        - pytest
        - pip
      commands:
        - pip check
        # TODO: figure out segfaults
        # - pytest -v tests/

  - name: gymnasium-atari
    build:
      # needs some as-yet unsolved packaging shenanigans
      # to actually install gymnasium.envs.atari
      skip: true
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gymnasium', exact=True) }}
        - ale-py >=0.8.0,<0.9
    test:
      imports:
        - gymnasium.envs.atari

  - name: gymnasium-box2d
    requirements:
      host:
        - python
        - swig ==4.*
      run:
        - python
        - {{ pin_subpackage('gymnasium', exact=True) }}
        - box2d-py ==2.3.*
        - pygame ==2.1.*
    test:
      imports:
        - gymnasium.envs.box2d

  - name: gymnasium-classic_control
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gymnasium', exact=True) }}
        - pygame ==2.1.*
    test:
      imports:
        - gymnasium.envs.classic_control

  - name: gymnasium-mujoco
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gymnasium', exact=True) }}
        - mujoco-python >=2.2.0,<2.4
        - imageio >=2.14.1
    test:
      imports:
        - gymnasium.envs.mujoco

  - name: gymnasium-mujoco_py
    build:
      # we currently don't have https://github.com/openai/mujoco-py
      # in conda-forge, and it'll be replaced by mujoco anyway
      skip: true
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gymnasium', exact=True) }}
        - mujoco-py >=2.1,<2.2
        - imageio >=2.14.1
    test:
      imports:
        - gymnasium.envs.mujoco

  - name: gymnasium-toy_text
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gymnasium', exact=True) }}
        - pygame ==2.1.*
    test:
      imports:
        - gymnasium.envs.toy_text

  - name: gymnasium-other
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gymnasium', exact=True) }}
        - lz4 >=3.1.0
        - matplotlib >=3.0
        - moviepy >=1.0
        - py-opencv >=3.0
    test:
      imports:
        # There are no tests in the source code for gymnasium-other

about:
  home: https://gymnasium.farama.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A standard API for reinforcement learning and a diverse set of reference environments (formerly Gym)
  dev_url: https://github.com/Farama-Foundation/Gymnasium

extra:
  recipe-maintainers:
    - h-vetinari
    - pseudo-rnd-thoughts
    - thewchan
  feedstock-name: gymnasium
