# Need these up here for conda-smithy to handle them properly.
schema_version: 1

context:
  version: 1.0.0

recipe:
  name: gymnasium-split
  version: ${{ version }}

source:
  url: https://github.com/Farama-Foundation/Gymnasium/archive/refs/tags/v${{ version }}.tar.gz
  sha256: d61a54c70d1960a0b64c63fe87edc30a0bac09551c27d8d94c36c54bf5fae5d9
  patches:
    # backport https://github.com/Farama-Foundation/Gymnasium/pull/1222
    - patches/1222.patch

build:
  number: 2
  python:
    version_independent: true

outputs:
  - package:
      name: gymnasium
    build:
      script: ${{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      build:
        - if: build_platform != target_platform
          then:
            - python ==${{ python_min }}
            - cross-python_${{ target_platform }}
      host:
        - python ==${{ python_min }}
        - pip
        - setuptools
      run:
        - python >=${{ python_min }}
        - numpy >=1.21.0
        - cloudpickle >=1.2.0
        - importlib-metadata >=4.8.0
        - typing_extensions >=4.3.0
        - farama-notifications >=0.0.1
    tests:
      - python:
          imports:
            - gymnasium

  - package:
      name: gymnasium-all
    requirements:
      host:
        - python ==${{ python_min }}
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('gymnasium-atari', exact=True) }}
        - ${{ pin_subpackage('gymnasium-box2d', exact=True) }}
        - ${{ pin_subpackage('gymnasium-classic_control', exact=True) }}
        - if: osx or (linux and not ppc64le)
          then: ${{ pin_subpackage('gymnasium-jax', exact=True) }}
        - ${{ pin_subpackage('gymnasium-mujoco', exact=True) }}
        # see below
        # - {{ pin_subpackage('gymnasium-mujoco_py', exact=True) }}
        - if: not ppc64le
          then: ${{ pin_subpackage('gymnasium-torch', exact=True) }}
        - ${{ pin_subpackage('gymnasium-toy_text', exact=True) }}
        - ${{ pin_subpackage('gymnasium-other', exact=True) }}
    tests:
      - python:
          python_version: ${{ python_min }}.*
          pip_check: true
          imports:
            - gymnasium
      - files:
          source:
            - scripts/
            - tests/
        requirements:
          run:
            - if: not (linux and aarch64)
              then: python ${{ python_min }}.*
            # older python version on linux aarch64 force a broken jaxlib version
            - if: linux and aarch64
              then: python 3.11
            - mock
            - pytest
            - scipy
            - dill
            - pip
            - if: not win
              then: mesalib
            # Just for tests a newer version of mujoco is required
            # See https://github.com/Farama-Foundation/Gymnasium/pull/1221#issuecomment-2424973616
            - mujoco-python >=2.3.6
        script:
          - if: unix
            then: scripts/test.sh
          - if: win
            then: scripts/test.bat

  - package:
      name: gymnasium-atari
    requirements:
      host:
        - python ==${{ python_min }}
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('gymnasium', exact=True) }}
        - ale-py >=0.9
    tests:
      - script:
          - echo "tested in ale-py"

  - package:
      name: gymnasium-box2d
    requirements:
      host:
        - python ==${{ python_min }}
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('gymnasium', exact=True) }}
        - box2d-py 2.3.*
        - pygame >=2.1.3
    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - gymnasium.envs.box2d

  - package:
      name: gymnasium-classic-control
    requirements:
      host:
        - python ==${{ python_min }}
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('gymnasium', exact=True) }}
        - pygame >=2.1.3
    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - gymnasium.envs.classic_control

  - package:
      name: gymnasium-classic_control
    requirements:
      host:
        - python ==${{ python_min }}
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('gymnasium-classic-control', exact=True) }}
    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - gymnasium.envs.classic_control

  - package:
      name: gymnasium-jax
    build:
      skip:
        - linux and ppc64le
        - win
    requirements:
      host:
        - python ==${{ python_min }}
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('gymnasium', exact=True) }}
        - jax >= 0.4.0
        - jaxlib >= 0.4.0
        - flax >= 0.5.0
    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - gymnasium.wrappers.jax_to_numpy

  - package:
      name: gymnasium-mujoco
    requirements:
      host:
        - python ==${{ python_min }}
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('gymnasium', exact=True) }}
        - mujoco-python >=2.1.5
        - imageio >=2.14.1
    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - gymnasium.envs.mujoco

  - package:
      name: gymnasium-mujoco-py
    build:
      # we currently don't have https://github.com/openai/mujoco-py
      # in conda-forge, and it'll be replaced by mujoco anyway
      skip: true
    requirements:
      host:
        - python ==${{ python_min }}
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('gymnasium', exact=True) }}
        - mujoco-py >=2.1,<2.2
        - imageio >=2.14.1
    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - gymnasium.envs.mujoco

  - package:
      name: gymnasium-torch
    build:
      skip: ppc64le
    requirements:
      host:
        - python ==${{ python_min }}
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('gymnasium', exact=True) }}
        - pytorch >= 1.0.0
    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - gymnasium.wrappers.numpy_to_torch

  - package:
      name: gymnasium-toy-text
    requirements:
      host:
        - python ==${{ python_min }}
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('gymnasium', exact=True) }}
        - pygame >=2.1.3
    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - gymnasium.envs.toy_text

  - package:
      name: gymnasium-toy_text
    requirements:
      host:
        - python ==${{ python_min }}
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('gymnasium-toy-text', exact=True) }}
    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - gymnasium.envs.toy_text

  - package:
      name: gymnasium-other
    requirements:
      host:
        - python ==${{ python_min }}
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('gymnasium', exact=True) }}
        - moviepy >=1.0
        - matplotlib-base >=3.0
        - py-opencv >=3.0
    tests:
      - script:
          - echo "no tests"

about:
  license: MIT
  license_file: LICENSE
  summary: A standard API for reinforcement learning and a diverse set of reference environments (formerly Gym)
  homepage: https://gymnasium.farama.org/
  repository: https://github.com/Farama-Foundation/Gymnasium

extra:
  recipe-maintainers:
    - h-vetinari
    - pseudo-rnd-thoughts
    - thewchan
    - traversaro
  feedstock-name: gymnasium
