schema_version: 1

context:
  version: 1.1.1

recipe:
  name: gymnasium-split
  version: ${{ version }}

source:
  url: https://github.com/Farama-Foundation/Gymnasium/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 7883c878c1ed5bcc7a5ba621ac859d23be9a26baea9f2a42596dc072143b0619
  patches:
    # backport https://github.com/Farama-Foundation/Gymnasium/pull/1361
    - patches/0001-Fix-jax-0.6.0-regression-in-jax_to_numpy-and-jax_to_.patch

build:
  number: 0

outputs:
  - package:
      name: gymnasium
    build:
      script: ${{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      build:
        - if: build_platform != target_platform
          then:
            - python
            - cross-python_${{ target_platform }}
            - numpy
      host:
        - python
        - pip
        - setuptools
        - cloudpickle >=1.2.0
        - numpy
      run:
        - python
        - cloudpickle >=1.2.0
        - farama-notifications
        - jax-jumpy >=1.0.0
        - typing_extensions >=4.3.0
    tests:
      - python:
          imports:
            - gymnasium

  - package:
      name: gymnasium-all
    requirements:
      host:
        - python
      run:
        - python
        - ${{ pin_subpackage('gymnasium-atari', exact=True) }}
        - ${{ pin_subpackage('gymnasium-box2d', exact=True) }}
        - ${{ pin_subpackage('gymnasium-classic_control', exact=True) }}
        - ${{ pin_subpackage('gymnasium-mujoco', exact=True) }}
        # see below
        # - {{ pin_subpackage('gymnasium-mujoco_py', exact=True) }}
        - ${{ pin_subpackage('gymnasium-toy_text', exact=True) }}
        - ${{ pin_subpackage('gymnasium-other', exact=True) }}
    tests:
      - python:
          pip_check: true
          imports:
            - gymnasium
      - files:
          source:
            - tests/
        requirements:
          run:
            - mock
            - pytest
            - scipy
            - dill
            - pip
            - if: unix and not ppc64le
              then:
                - jax >=0.4
                - flax >=0.5.0
            - if: linux
              then: mesalib
            # Just for tests a newer version of mujoco is required
            # See https://github.com/Farama-Foundation/Gymnasium/pull/1221#issuecomment-2424973616
            - mujoco-python >=2.3.6
        script:
          - pip check
          - if: unix
            then: |
              tests_to_skip="_not_a_real_test"
              # These test requires mujoco_py, see https://github.com/conda-forge/gymnasium-feedstock/pull/36#issuecomment-2124082918
              tests_to_skip="$tests_to_skip or test_verify_info_x_position"
              tests_to_skip="$tests_to_skip or test_verify_info_y_position"
              tests_to_skip="$tests_to_skip or test_verify_info_x_velocity"
              tests_to_skip="$tests_to_skip or test_verify_info_y_velocity"
              tests_to_skip="$tests_to_skip or test_verify_info_xy_velocity_xpos"
              tests_to_skip="$tests_to_skip or test_verify_info_xy_velocity_com"
              tests_to_skip="$tests_to_skip or test_set_state"
              tests_to_skip="$tests_to_skip or test_distance_from_origin_info"
              tests_to_skip="$tests_to_skip or test_model_sensors"
              tests_to_skip="$tests_to_skip or test_reset_noise_scale"
              # These tests do not run on CI due to missing window system, see https://github.com/conda-forge/gymnasium-feedstock/pull/36#issuecomment-2124183361
              tests_to_skip="$tests_to_skip or test_max_geom_attribute[10-human]"
              tests_to_skip="$tests_to_skip or test_max_geom_attribute[100-human]"
              tests_to_skip="$tests_to_skip or test_max_geom_attribute[1000-human]"
              tests_to_skip="$tests_to_skip or test_max_geom_attribute[10000-human]"
          - if: win
            then: |
              set tests_to_skip="_not_a_real_test"
              REM These test requires mujoco_py, see https://github.com/conda-forge/gymnasium-feedstock/pull/36#issuecomment-2124082918
              set tests_to_skip=%tests_to_skip% or test_verify_info_x_position
              set tests_to_skip=%tests_to_skip% or test_verify_info_y_position
              set tests_to_skip=%tests_to_skip% or test_verify_info_x_velocity
              set tests_to_skip=%tests_to_skip% or test_verify_info_y_velocity
              set tests_to_skip=%tests_to_skip% or test_verify_info_xy_velocity_xpos
              set tests_to_skip=%tests_to_skip% or test_verify_info_xy_velocity_com
              set tests_to_skip=%tests_to_skip% or test_set_state
              set tests_to_skip=%tests_to_skip% or test_distance_from_origin_info
              set tests_to_skip=%tests_to_skip% or test_model_sensors
              set tests_to_skip=%tests_to_skip% or test_reset_noise_scale
              REM These tests do not run on CI due to missing window system, see https://github.com/conda-forge/gymnasium-feedstock/pull/36#issuecomment-2124183361
              set tests_to_skip=%tests_to_skip% or test_max_geom_attribute[10-human]
              set tests_to_skip=%tests_to_skip% or test_max_geom_attribute[100-human]
              set tests_to_skip=%tests_to_skip% or test_max_geom_attribute[1000-human]
              set tests_to_skip=%tests_to_skip% or test_max_geom_attribute[10000-human]
              REM The following tests fail as for mujoco the osmesa rendering backend is only supported on Linux
              REM See https://github.com/conda-forge/gymnasium-feedstock/pull/41#issuecomment-2428691450
              set tests_to_skip=%tests_to_skip% or test_offscreen_viewer_custom_dimensions
              set tests_to_skip=%tests_to_skip% or test_max_geom_attribute
              set tests_to_skip=%tests_to_skip% or test_camera_id
              set tests_to_skip=%tests_to_skip% or test_num_envs_screen_size
              REM started with v1.1.1
              set tests_to_skip=%tests_to_skip% or test_rgbd_tuple"
          - if: osx
            then: |
              # the following pygame tests are skipped [according to selector], because there is no rendering support during the CI build
              tests_to_skip="$tests_to_skip or test_human_rendering"
              tests_to_skip="$tests_to_skip or test_keyboard_irrelevant_keydown_event"
              tests_to_skip="$tests_to_skip or test_keyboard_keyup_event"
              tests_to_skip="$tests_to_skip or test_keyboard_quit_event"
              tests_to_skip="$tests_to_skip or test_keyboard_relevant_keydown_event"
              tests_to_skip="$tests_to_skip or test_no_error_warnings[env0]"
              tests_to_skip="$tests_to_skip or test_no_error_warnings[env1]"
              tests_to_skip="$tests_to_skip or test_play_loop_real_env"
              tests_to_skip="$tests_to_skip or test_play_relevant_keys"
              tests_to_skip="$tests_to_skip or test_pygame_quit_event"
              tests_to_skip="$tests_to_skip or test_video_size_no_zoom"
              tests_to_skip="$tests_to_skip or test_video_size_zoom"
              # The following tests fail as for mujoco the osmesa rendering backend is only supported on Linux
              # See https://github.com/conda-forge/gymnasium-feedstock/pull/41#issuecomment-2428691450
              tests_to_skip="$tests_to_skip or test_offscreen_viewer_custom_dimensions"
              tests_to_skip="$tests_to_skip or test_max_geom_attribute"
              tests_to_skip="$tests_to_skip or test_camera_id"
              tests_to_skip="$tests_to_skip or test_num_envs_screen_size"
              # started with v1.1.1
              tests_to_skip="$tests_to_skip or test_rgbd_tuple"
          - if: aarch64
            then: |
              # See https://github.com/conda-forge/gymnasium-feedstock/pull/32#issuecomment-2031810613
              tests_to_skip="$tests_to_skip or test_render_modes"
          # atary test are skipped as we do not have atari ROMs in the CI
          # See https://github.com/conda-forge/gymnasium-feedstock/pull/41#issuecomment-2404215826
          - if: unix
            then: rm tests/wrappers/test_atari_preprocessing.py
          - if: win
            then: del tests\\wrappers\\test_atari_preprocessing.py
          # need to specify opengl driver on linux to enable offscreen rendering in MuJoCo
          - if: linux
            then: export MUJOCO_GL="osmesa"
          # Workaround for https://github.com/conda-forge/gymnasium-feedstock/pull/50#issuecomment-3218125344
          - if: aarch64
            then: export LD_PRELOAD=libGLdispatch.so.0
          # Ensure that pygame tests pass on unix,
          # see https://github.com/conda-forge/gymnasium-feedstock/pull/36#issuecomment-2124699477
          - if: unix
            then: export SDL_VIDEODRIVER="dummy"
          - if: unix
            then: pytest -v tests/ --durations=50 -k "not ($tests_to_skip)"
          - if: win
            then: pytest -v tests/ --durations=50 -k "not (%tests_to_skip%)"

  - package:
      name: gymnasium-atari
    requirements:
      host:
        - python
      run:
        - python
        - ${{ pin_subpackage('gymnasium', exact=True) }}
        - ale-py >=0.9
    tests:
      - script:
          - echo "tested in ale-py"

  - package:
      name: gymnasium-box2d
    requirements:
      host:
        - python
        - swig 4.*
      run:
        - python
        - ${{ pin_subpackage('gymnasium', exact=True) }}
        - box2d-py 2.3.*
        - pygame >=2.1.3
    tests:
      - python:
          imports:
            - gymnasium.envs.box2d

  - package:
      name: gymnasium-classic_control
    requirements:
      host:
        - python
      run:
        - python
        - ${{ pin_subpackage('gymnasium', exact=True) }}
        - pygame >=2.1.3
    tests:
      - python:
          imports:
            - gymnasium.envs.classic_control

  - package:
      name: gymnasium-mujoco
    requirements:
      host:
        - python
      run:
        - python
        - ${{ pin_subpackage('gymnasium', exact=True) }}
        - mujoco-python >=2.1.5
        - imageio >=2.14.1
    tests:
      - python:
          imports:
            - gymnasium.envs.mujoco

  - package:
      name: gymnasium-mujoco_py
    build:
      # we currently don't have https://github.com/openai/mujoco-py
      # in conda-forge, and it'll be replaced by mujoco anyway
      skip: true
    requirements:
      host:
        - python
      run:
        - python
        - ${{ pin_subpackage('gymnasium', exact=True) }}
        - mujoco-py >=2.1,<2.2
        - imageio >=2.14.1
    tests:
      - python:
          imports:
            - gymnasium.envs.mujoco

  - package:
      name: gymnasium-toy_text
    requirements:
      host:
        - python
      run:
        - python
        - ${{ pin_subpackage('gymnasium', exact=True) }}
        - pygame >=2.1.3
    tests:
      - python:
          imports:
            - gymnasium.envs.toy_text

  - package:
      name: gymnasium-other
    requirements:
      host:
        - python
      run:
        - python
        - ${{ pin_subpackage('gymnasium', exact=True) }}
        - lz4 >=3.1.0
        - matplotlib >=3.0
        - moviepy >=1.0
        - py-opencv >=3.0
        - if: unix and not ppc64le
          then: pytorch >=1.0
    tests:
      - script:
          - echo "no tests"

about:
  license: MIT
  license_file: LICENSE
  summary: A standard API for reinforcement learning and a diverse set of reference environments (formerly Gym)
  homepage: https://gymnasium.farama.org/
  repository: https://github.com/Farama-Foundation/Gymnasium

extra:
  recipe-maintainers:
    - h-vetinari
    - pseudo-rnd-thoughts
    - thewchan
    - traversaro
  feedstock-name: gymnasium
